# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e46cb5c8c70a5fd7953a2bfd70b7255b064392a9d8a6c583c93fe7aef7cb146df45fab364f70f87a8424248e3bc59efca13ed1a59606968fa1ccf0f68cd0979b

test:
  secret_key_base: 78690c3f485453436e9ad9e47072df3f92c4f11763353df61ce33cc827642cf4eb24164548611ca60f761fefabebca60969ea3963260e36cb3f8d2f36e3c4ea3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
